# Copyright 2021 Canonical Ltd.
# Licensed under the GPLv3, see LICENSE file for details.

options:
  controller-url:
    default: ""
    description: The URL used to access the controller API.
    type: string
  identity-provider-url:
    default: ""
    description: The URL used to access an external identity provider.
    type: string
  is-juju:
    default: true
    description: Whether this is a standalone Juju controller
    type: boolean
