[project]
name = "juju-controller"
version = "0.1.0"
requires-python = ">=3.8"
dependencies = [
    "ops",
    "charmhelpers",
    "cosl",
]

[project.optional-dependencies]
dev = [
    "coverage",
    "flake8",
]
